import { TechStack, Project } from './types';

export const techStack: TechStack[] = [
  { name: 'Microsoft Azure', shortName: 'Az', color: 'bg-blue-600', logo: '/tech-logos/azure.svg' },
  { name: 'Databricks', shortName: 'DB', color: 'bg-red-500', logo: '/tech-logos/databricks.svg' },
  { name: 'Azure Data Factory', shortName: 'ADF', color: 'bg-blue-500' },
  { name: 'Python', shortName: 'Py', color: 'bg-yellow-500', logo: '/tech-logos/python.svg' },
  { name: 'Tableau', shortName: 'TB', color: 'bg-blue-400', logo: '/tech-logos/tableau.svg' },
  { name: 'Power BI', shortName: 'PBI', color: 'bg-yellow-600', logo: '/tech-logos/powerbi.svg' },
  { name: 'Kubernetes', shortName: 'K8s', color: 'bg-blue-700', logo: '/tech-logos/kubernetes.svg' },
  { name: 'Microsoft Purview', shortName: 'MP', color: 'bg-purple-600' },
  { name: 'Github Copilot', shortName: 'GH', color: 'bg-gray-800', logo: '/tech-logos/github.svg' },
  { name: 'Apache Spark', shortName: '⚡', color: 'bg-orange-600', logo: '/tech-logos/apache-spark.svg' },
  { name: 'Cursor AI', shortName: 'CR', color: 'bg-blue-500' },
  { name: 'Claude Code', shortName: 'CL', color: 'bg-purple-500' },
  { name: 'n8n', shortName: 'n8n', color: 'bg-pink-500', logo: '/tech-logos/n8n.svg' },
  { name: 'SQL', shortName: 'SQL', color: 'bg-gray-700' },
  { name: 'DevOps', shortName: 'DO', color: 'bg-green-600' },
  { name: 'CI/CD', shortName: 'CI', color: 'bg-indigo-600' },
  { name: 'DeepSeek', shortName: 'DS', color: 'bg-red-600' },
  { name: 'MCP', shortName: 'MCP', color: 'bg-teal-600' },
  { name: 'Next.js', shortName: '▲', color: 'bg-black', logo: '/tech-logos/nextjs.svg' },
  { name: 'Node.js', shortName: 'N', color: 'bg-green-600', logo: '/tech-logos/nodejs.svg' },
  { name: 'NotebookLM', shortName: 'NB', color: 'bg-blue-600' },
  { name: 'MongoDB', shortName: 'M', color: 'bg-green-500', logo: '/tech-logos/mongodb.svg' },
  { name: 'React', shortName: '⚛', color: 'bg-blue-500', logo: '/tech-logos/react.svg' },
  { name: 'TypeScript', shortName: 'TS', color: 'bg-blue-600', logo: '/tech-logos/typescript.svg' },
  { name: 'PostgreSQL', shortName: 'PG', color: 'bg-blue-700', logo: '/tech-logos/postgresql.svg' },
  { name: 'Stripe', shortName: '$', color: 'bg-purple-600', logo: '/tech-logos/stripe.svg' },
  { name: 'Redis', shortName: 'R', color: 'bg-red-600', logo: '/tech-logos/redis.svg' },
  { name: 'Docker', shortName: '🐳', color: 'bg-blue-500', logo: '/tech-logos/docker.svg' },
  { name: 'OpenAI', shortName: 'AI', color: 'bg-green-600', logo: '/tech-logos/openai.svg' },
  { name: 'Socket.io', shortName: '⚡', color: 'bg-gray-800', logo: '/tech-logos/socketio.svg' },
  { name: 'TailwindCSS', shortName: 'TW', color: 'bg-cyan-500', logo: '/tech-logos/tailwindcss.svg' },
];

export const projects: Project[] = [
  {
    id: 'ecommerce-platform',
    title: 'ShopCraft - Modern E-commerce Platform',
    description: 'A comprehensive full-stack e-commerce solution featuring responsive design, secure payment processing, real-time inventory management, and advanced analytics. Built with modern technologies for optimal performance and scalability.',
    image: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['React', 'Next.js', 'Node.js', 'TypeScript', 'PostgreSQL', 'Stripe', 'Redis', 'Docker'],
    link: 'https://shopcraft-demo.hermanteng.dev',
    github: 'https://github.com/hermanteng/shopcraft-ecommerce',
    featured: true,
  },
  {
    id: 'task-management-app',
    title: 'Task Management App',
    description: 'Collaborative task management with real-time updates and team features.',
    image: 'https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['Next.js', 'Firebase', 'Tailwind'],
    link: 'https://taskmaster-demo.hermanteng.dev',
    github: 'https://github.com/hermanteng/task-management-app',
    featured: true,
  },
  {
    id: 'data-visualization-dashboard',
    title: 'Data Visualization Dashboard',
    description: 'Interactive dashboard for complex data analysis and reporting.',
    image: 'https://images.pexels.com/photos/669619/pexels-photo-669619.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['D3.js', 'React', 'Python'],
    link: 'https://dataviz-demo.hermanteng.dev',
    github: 'https://github.com/hermanteng/data-viz-dashboard',
    featured: true,
  },
  {
    id: 'mobile-banking-app',
    title: 'Mobile Banking App',
    description: 'Secure mobile banking interface with advanced security features.',
    image: 'https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['React Native', 'TypeScript', 'REST API'],
    link: 'https://mobile-banking-demo.hermanteng.dev',
    github: 'https://github.com/hermanteng/mobile-banking-app',
    featured: true,
  },
  {
    id: 'analytics-dashboard',
    title: 'Analytics Dashboard',
    description: 'Full-stack dashboard with real-time analytics and comprehensive data visualization',
    image: 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['React', 'Node.js', 'D3.js', 'PostgreSQL'],
    link: 'https://analytics-demo.hermanteng.dev',
    github: 'https://github.com/hermanteng/analytics-dashboard',
    featured: true,
  },
  {
    id: 'ai-notes-app',
    title: 'NoteGenius - AI-Powered Online Notes App',
    description: 'An intelligent note-taking application that leverages AI to enhance productivity. Features include smart categorization, automatic summarization, content suggestions, voice-to-text transcription, and collaborative editing with real-time AI assistance.',
    image: 'https://images.pexels.com/photos/1591061/pexels-photo-1591061.jpeg?auto=compress&cs=tinysrgb&w=600',
    technologies: ['React', 'Next.js', 'TypeScript', 'Node.js', 'OpenAI', 'MongoDB', 'Socket.io', 'TailwindCSS'],
    link: 'https://notegenius-ai.hermanteng.dev',
    github: 'https://github.com/hermanteng/notegenius-ai',
    featured: true,
  },
];

export const featuredProject = projects.find(p => p.id === 'ecommerce-platform') || projects[0];

export const profileInfo = {
  name: 'Herman Teng',
  title: 'Senior Data Engineer & Tech Blogger',
  subtitle: 'Building the future of web experiences',
  profileImage: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=300',
  aboutImage: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=600',
  bio: {
    intro: "I'm a passionate front-end architect and tech blogger with over 8 years of experience building scalable web applications. I specialize in modern JavaScript frameworks, performance optimization, and creating exceptional user experiences.",
    personal: "When I'm not coding, you can find me exploring new technologies, writing technical articles, or traveling to discover new cultures and perspectives. I believe that great software comes from understanding both the technical and human aspects of development.",
    collaboration: "I'm always excited to collaborate on innovative projects and share knowledge with the development community through my blog and open-source contributions.",
  },
}; 